blank_issues_enabled: false
contact_links:
  - name: AAIF Project Proposal Support
    url: https://discord.gg/9zTwngHAMy
    about: Questions about project proposals or the AAIF that aren't a proposal? Reach AAIF staff on the AAIF Discord server.
